//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace img_detective.ui.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public long Id { get; set; }
        public Nullable<int> RepositoryId { get; set; }
        public string Path { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Description { get; set; }
    
        public virtual repository repository { get; set; }
    }
}
