//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace img_detective.ui.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class repository
    {
        public repository()
        {
            this.images = new HashSet<image>();
        }
    
        public int Id { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<image> images { get; set; }
    }
}
